---
title: "Movies Dashboard"
output: 
  flexdashboard::flex_dashboard:
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard) 
library(tidyverse)
library(mgcv)
library(DT)
library(lubridate)
knitr::opts_chunk$set(fig.width = 5)
```

# Movies

```{r data-loading-chunk}

load("../data/cleaned_data/full_IMDb_Scrape.Rdata")#data name movies

movies <- movies |>
  filter(votes>=10000)

# Source relevant scripts
source("../scripts/scrapping_functions/enrich_dob.R")
source("../scripts/scrapping_functions/enrich_studio_and_budget.R")


# Load and aggregate data switch load with functions to try on new data set

#dob_table_stars_cleaned <- find_dob( movies |> select(stars) |>
#                       separate_rows(stars, sep = ",\\s*")|>
#                       unique()) |> mutate(dob_stars = ymd(dob))
load("../data/cleaned_data/dob_stars10k_cleaned.Rdata")


#dob_table_directors_cleaned <- find_dob( movies |> select(directors) |>
#                        separate_rows(directors, sep = ",\\s*")|> 
#                        unique()) |> mutate(dob_directors = ymd(dob))
load("../data/cleaned_data/dob_directors10k_cleaned.Rdata")


#studio_and_budget <- enrich_studio_and_budget(movies[,c("title","year")])
load("../data/scrapped_data/studio_and_budget10k.Rdata")#data name dob_table_directors


#source("../scripts/cleaning_functions/clean_studio_budget.R") #Cleaning the studio takes about 1.5 hours for >10k votes
load("../data/cleaned_data/studio_and_budget10k_cleaned.Rdata")


# Apparently the dot operator needs %>% not yet implemented in base r using |>
CPI <- read.csv("../data/cleaned_data/inflation.csv") %>%
    mutate(CPI = rowMeans(.[,3:14],na.rm=T)) %>%
    select(Year,CPI) %>%
    rbind(data.frame(Year = 2023,CPI = 302.340)) #US Federal Reserve Economic Data

# integrate population data
population <- read.csv("../data/cleaned_data/population.csv")
population_gam <- gam(population~s(census_year),data = population)
predictions <- predict(object = population_gam, newdata = data.frame(census_year = seq(1900, 2023, 1)))
population_estimates <- data.frame(year = seq(1900, 2023, 1),
                                   population = predictions)


#aggregate data + make it TIDY (Split per per Genre, Actor, Director and Studio)
#Warning is due two films "Beast 2022" when doing a left join, we adjust them afterwards.
suppressWarnings({
movies <- movies |> 
  left_join(CPI,join_by(year==Year)) |>
  left_join(studio_and_budget_cleaned[1:4], join_by(title,year)) |>
  separate_rows(stars, sep = ",\\s*") |>
  left_join(dob_table_stars_cleaned[1:2],join_by(stars)) |>
  separate_rows(directors, sep = ",\\s*") |>
  left_join(dob_table_directors_cleaned[1:2],join_by(directors)) |>
  separate_rows(genre, sep = ",\\s*") |>
  left_join(population_estimates, join_by(year))
})

# There are two movies named beast from the year 2022.
movies[movies$title=="Beast" & movies$run_time ==93,"budget"] <- 36e6
movies[movies$title=="Beast" & movies$run_time ==93,"studio"] <- "Universal Pictures"
genres <- unique(movies$genre)
```

## Column 1 {data-width=150}

### Genre Filter {data-height=500}

```{r}
checkboxGroupInput("genreFilter", "Select Genre:", choices = genres, selected = "All")
```


## Column 2

### Movies Evolution

```{r}

fit_genre <- function(genreVector,genre_collapsed){
  fits <- T
  for(current_genre in genreVector){
    fits <- fits & grepl(pattern = current_genre,x=genre_collapsed)
  }
  return(fits)
}



filtered_movies <- reactive({
  selected_genres <- input$genreFilter

  if (length(selected_genres) == 0) { #or if("All" %in% selected_genres) but we want none!
    # If "All" is selected, show all genres
    filtered_data <- movies |>
      distinct(title, year, rating, stars,directors)
  } else {
    # If specific genres are selected, filter based on those genres
    filtered_data <- movies |>
        distinct(title, year, genre, rating, stars,directors) |>
        group_by(title, year, rating, stars,directors) |>
        mutate(genre = paste(unique(genre), collapse = ",")) |>
        ungroup()|>
        unique() |>
        mutate(matched_genre = fit_genre(selected_genres,genre)) |>
      filter(matched_genre)
  }

  return(filtered_data)
})

output$moviesPlot <- renderPlot({
  filtered_data <- filtered_movies()
  filtered_data |>
    distinct(title,year) |>
    group_by(year) |>
    summarise(
      count = n()) |>
    ggplot(aes(x = year,y=count)) +
    #geom_line(aes(y = nr_missing_values), col = "red") +
    geom_line(col = "blue") +
    scale_x_continuous(breaks = seq(1915, 2025, 6)) +
    labs(
      y = "Number of Featured Films"
    ) +
    #annotate("text", x = 1915, y = 350, vjust = "bottom", hjust = "left",
    #         label = "Total", color = "blue") +
    #annotate("text", x = 1915, y = 320, vjust = "bottom", hjust = "left",
    #         label = "Incl. Gross", color = "red") +
    theme_minimal() #+
    #theme(axis.text.x = element_text(angle = 45, hjust = 1))
})

plotOutput("moviesPlot")

```


## Column 3{data-width=400}

### The Top Rated Movies

```{r}
# output$movies_table <- renderDT({
#   filtered_data <- filtered_movies()
#   # Assuming you have a data frame called "filtered_data"
#   datatable(
#     filtered_data %>%
#       distinct(title,year,rating)%>%
#       arrange(desc(rating)) %>%
#       head(100) %>%
#       select(title, year, rating),
#     options = list(
#       # Customize datatable options here, e.g., search, paging, etc.
#       pageLength = 10,
#       searching = TRUE
#     )
#   )
# })
# DTOutput("movies_table")
output$movies_table <- renderDT({
  filtered_data <- filtered_movies()
  # Assuming you have a data frame called "filtered_data"
  datatable(
    filtered_data %>%
      distinct(title, year, rating) %>%
      arrange(desc(rating)) %>%
      head(100) %>%
      select(title, year, rating),
    options = list(
      pageLength = 10,
      searching = FALSE, # Remove the search bar
      lengthChange = FALSE, # Remove the 'Show X entries' dropdown
      ordering = TRUE, # Remove sorting
      info = FALSE # Remove table information
    )
  )
})
DTOutput("movies_table")

```

### Famous Actors

```{r}

output$actorsTable <- renderDT({
  filtered_data <- filtered_movies()
  # Assuming you have a data frame called "filtered_data"
  datatable(
    filtered_data %>%
      select(stars,rating) %>%
      group_by(stars)%>%
      summarise(rating = mean(rating),
                count = n()) %>% 
      ungroup() %>%
      arrange(desc(rating)) %>%
      head(100) %>%
      select(stars, count,rating),
    options = list(
      pageLength =10,
      searching = FALSE,
      lengthChange = FALSE,
      info = FALSE
    )
  )
})
DTOutput("actorsTable")

```


### Famous Directors

```{r}

output$directorsTable <- renderDT({
  filtered_data <- filtered_movies()
  # Assuming you have a data frame called "filtered_data"
  datatable(
    filtered_data %>%
      select(directors,rating) %>%
      group_by(directors)%>%
      summarise(rating = mean(rating),
                count = n()) %>% 
      ungroup() %>%
      arrange(desc(rating)) %>%
      head(100) %>%
      select(directors, count,rating),
    options = list(
      pageLength =10,
      searching = FALSE,
      lengthChange = FALSE,
      info = FALSE
    )
  )
})
DTOutput("directorsTable")

```


# Actors

## Column 1

### Actor Search {data-height=100}
```{r}
textInput("starFilter", "Actor Name:")

starFilter <- unique(movies$stars) |> tolower()

filtered_movies2 <- reactive({
  selected_actor <- input$starFilter |> tolower()

  if (length(selected_actor) == 0) {
    # If no specific actor is selected, show all records
    filtered_data <- movies |>
      distinct(title, year, rating, stars, directors,dob_stars)
  } else {
    # If a specific actor is selected, filter based on that actor
    filtered_data <- movies |> 
      mutate(stars = tolower(stars)) |> 
      distinct(title, year, genre, rating, stars, directors,dob_stars) |>
      filter(stars %in% selected_actor)
  }

  return(filtered_data)
})

```
### Actor Date of Birth

```{r}
renderValueBox({
  filtered_data <- filtered_movies2()
  b <- filtered_data %>%
    select(dob_stars) %>% slice(1)

  valueBox(value = b[[1]], icon = "Date of Birth")
})
#first_dob_entry <- filtered_data |> select(dob_stars) |> slice(1)

```



### Movie Titles

```{r}

output$actorsTable2 <- renderDT({
  filtered_data <- filtered_movies2()
  # Assuming you have a data frame called "filtered_data"
  datatable(
    filtered_data %>%
      select(title,year,rating) %>%
      unique(),
    options = list(
      pageLength =10,
      searching = FALSE,
      lengthChange = FALSE,
      info = FALSE
    )
  )
})
DTOutput("actorsTable2")


```

## Column 2

### Number of movies
```{r}

output$starAppearancePlot <- renderPlot({
  filtered_data <- filtered_movies2()
  if (length(unique(filtered_data$stars))==1) {
    # Generate and render the plot only if a filter is selected
    first_dob_entry <- filtered_data |> select(dob_stars) |> slice(1)
    yob <- year(first_dob_entry[[1]])
    career_table <- data.frame(age = seq(0, 2023 - yob, by = 1))

    career_table <- career_table |> left_join(filtered_data |>
      distinct(title, year, rating, dob_stars) |>
      group_by(year, dob_stars) |>
      summarise(
        count = n()
      ) |>
      mutate(age = year - year(dob_stars)), join_by(age))

    career_table$count = if_else(is.na(career_table$count), 0, career_table$count)
    career_table$countPlus = cumsum(career_table$count)

    ggplot(aes(x = age, y = countPlus), data = career_table) +
      geom_line(col = "blue") +
      labs(
        y = "Number Of Featured Movies"
      ) +
      theme_minimal()
  } else {
    # Display a message or an empty plot if no filter is selected
    # For example, you can return an empty plot
    #plot(1, type = "n", xlab = "", ylab = "")
  }
})

plotOutput("starAppearancePlot")

```



### Career Average Rating

```{r}

output$starCareerPlot <- renderPlot({
  filtered_data <- filtered_movies2()
  filtered_data |>
    distinct(title,year,rating) |>
    group_by(year) |>
    summarise(
      count = n(),
      rating = mean(rating)) |>
    ggplot(aes(x = year,y=rating)) +
    #geom_line(aes(y = nr_missing_values), col = "red") +
    geom_line(col = "blue") +
    scale_x_continuous(breaks = seq(1915, 2025, 6)) +
    labs(
      y = "Average Rating"
    ) +
    #annotate("text", x = 1915, y = 350, vjust = "bottom", hjust = "left",
    #         label = "Total", color = "blue") +
    #annotate("text", x = 1915, y = 320, vjust = "bottom", hjust = "left",
    #         label = "Incl. Gross", color = "red") +
    theme_minimal() #+
    #theme(axis.text.x = element_text(angle = 45, hjust = 1))
})

plotOutput("starCareerPlot")


```


## Column 3
### Career with Co-actors

```{r}

output$actorsTable4 <- renderDT({
  filtered_data <- filtered_movies2()
  # Assuming you have a data frame called "filtered_data"
  datatable(
    filtered_data |>
    distinct(title,stars) |>
    left_join(movies |> distinct(title,year,stars),join_by(title)) |>
    group_by(co_actors = stars.y) |>
    summarise(count = n()) |>
    arrange(desc(count)) |>
    slice(-1), #get rid of ones self.
    options = list(
      pageLength =10,
      searching = FALSE,
      lengthChange = FALSE,
      info = FALSE
    )
  )
})
DTOutput("actorsTable4")

```

### Career with Co-directors
```{r}

output$actorsTable3 <- renderDT({
  filtered_data <- filtered_movies2()
  # Assuming you have a data frame called "filtered_data"
  datatable(
    filtered_data |>
    distinct(title,directors,rating) |>
    group_by(directors) |>
    summarise(
      count = n(),
      rating = mean(rating))|>
      arrange(desc(rating)),
    options = list(
      pageLength =10,
      searching = FALSE,
      lengthChange = FALSE,
      info = FALSE
    )
  )
})
DTOutput("actorsTable3")

```

# Recommend Me A Movie! <!---(comment: {data-navmenu=More} to have dropdown called more with page inside)-->

```{r}

 
actionButton("execute", "Recommend")

observeEvent(input$execute, {
    # When the "Recommend" button is pressed
    random_number <- sample(1:250, 1)

output$recommendation_table <- renderDT({
  
  datatable(
    movies |> distinct(title,year,run_time,genre,stars,directors,rating,metascore,certificate) |>
    group_by(title, year, run_time, rating, metascore, certificate) |>
    mutate(stars = paste(unique(stars), collapse = ", "),
         directors = paste(unique(directors), collapse = ", "),
         genre = paste(unique(genre), collapse = ", ")) |>
    ungroup() |>
    unique()|>
    slice(random_number),
    options = list(
      pageLength =1,
      searching = FALSE,
      lengthChange = FALSE,
      info = FALSE
    )
  )
})
})
DTOutput("recommendation_table")

```
